name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Hello world action step
      id: hello
      uses: PavelBansky/test-3000/upload@v1.6
      with:
        user_name: 'John Francis Doe'
      # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
       skip-queries: true
       
