name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: csharp
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
       skip-queries: true
       
       
    - name: Upload Database
      uses: microsoft-sdl/codeql-actions/upload@main
      with:
        proxy-endpoint: https://fe-lgtmproxy-test-1.azurewebsites.net
        metadata: CODEQL_BuildIdentifier=mybuild2
        build-identifier-keys: CODEQL_BuildIdentifier
        
    #- name: Upload action step
    #  uses: PavelBansky/test-3000/upload@v1.7
    #  with:
    #    user_name: 'John Francis Doe'     
       
